services:

  facade:
    image: ${FACADE_IMAGE}
    container_name: facade-container
    restart: unless-stopped
    expose:
      - ${FACADE_INNER_PORT}

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui-container
    hostname: facade-host
    volumes:
      - ./db/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
    expose:
      - "2053"
      - "2096"
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    container_name: caddy-container
    hostname: caddy-host
    restart: unless-stopped
    ports:
      - "80:80"
      - "2021:2021" # legacy subscriptions
      - ${XPANEL_FALLBACK_PORT}:${XPANEL_FALLBACK_PORT}
    expose:
      - "443"
      - "443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - FACADE_INNER_PORT=${FACADE_INNER_PORT}
      - LEGACY_DOMAIN=${LEGACY_DOMAIN}
      - XPANEL_PATH_POSTFIX=${XPANEL_PATH_POSTFIX}
      - XPANEL_FALLBACK_PORT=${XPANEL_FALLBACK_PORT}
    depends_on:
      - facade

volumes:
  caddy_data: # This volume contains certs. Copy it when redeploying to prevent reissuing and rate limiting.
  caddy_config: # Contains dynamic configuration, if it was created in run-time. Usually not needed.
  db: # Contains the database for 3x-ui.

